baseURL = "https://saultcollege-mysql-syntax-basics.netlify.com"
languageCode = "en-us"
title = "MySQL Syntax Basics"
theme = ["hugo-book"]

[markup.goldmark.renderer] 
    unsafe = true 

[markup.highlight]
    style = "xcode"

[Params]
    menu_style = "slide-menu"